export default{
    isUserName:true,
    loginInput:{
        userName:'',
        password:'',
    },
    registerPro:{
        userName:'',
        email:'',
        phone:'',
        password:'',
        confirmPass:'',
        topics:[],
        image:{},
    },
    registerBasic:{
        userName:'',
        email:'',
        phone:'',
        password:'',
        confirmPass:'',
        topics:[],
        image:{},
    }
}